### ISSUE TITLE
Wallet Balance  = 0 and Transaction Histories are too..

### ISSUE THREAD

**Issue by onurormen** [iotaledger/wallet#1062]
Hello,
My computer was closed on last weekend. When I open the iota wallet with the seed that I always use, I see that the balance is zero and the transaction histories are zero too. 
What could be the reason for this?

PS : 
Node info  Host : http://node06.iotatoken.nl:14265

**Comment by lbux** [comment]
Please read [this](https://medium.com/@ralf/prepare-for-the-january-28-2018-iota-snapshot-10f565b371ab). Try using [Reddit](https://www.reddit.com/r/Iota/) or the [IOTA forums](https://forum.iota.org/) next time, GitHub isn't the place to post these kinds of issues.

**Comment by prinsleo** [comment]
Because your account is stolen alle funds.

Fra: onurormen [mailto:notifications@github.com]
Sendt: mandag 29. januar 2018 10:08
Til: iotaledger/wallet <wallet@noreply.github.com>
Kopi: Subscribed <subscribed@noreply.github.com>
Emne: [iotaledger/wallet] Wallet Balance = 0 and Transaction Histories are too.. (#1062)


Hello,
My computer was closed on last weekend. When I open the iota wallet with the seed that I always use, I see that the balance is zero and the transaction histories are zero too.
What could be the reason for this?

PS :
Node info Host : http://node06.iotatoken.nl:14265
