### ISSUE TITLE
0 balance

### ISSUE THREAD

**Issue by RPL961** [iotaledger/wallet#1115]
### Prerequisites
If you are **not** suggesting a feature, you must be able to check all of the following (place an x inside the brackets to check the box). If you cannot check all of the boxes, this issue should not be reported on GitHub as it is not a bug:

* [x] I confirm that this is an issue with the IOTA Wallet and not an exchange
* [x] I confirm that this is an issue with the wallet, not IRI
* [x] For pending transactions: I confirm that I have tried reattaching and promoting multiple times (check this box if your issue is not related to a pending transaction)
* [ ] I confirm that this is not an issue related to stolen/lost funds
* [x] I confirm that this is not a zero balance issue related to a snapshot (last snapshots occurred on October 23 and January 28)
* [x] For private key warnings: I confirm that I am not at risk of reusing an address, or another user has verified that I am not (check this box if your issue is not related to a private key reuse)
* [x] I confirm that this issue is present on the latest version of the wallet

### Description

[balance showing zero]

### Steps to Reproduce

1. [attach reattach, promote, create new receving address]
2. [I suspect my iota wallet was hacked, my funds have been transferred to a very suspicious address: NOFUKFKSLVRB9DFNRIXBKEQ9PQJLLONOTJHGFJZJHIPOBBMLTJPNPDKKCVXJIMZYKBOGWGCKXPWTIXXLCKENOEL9JD, who can help me?..
my original receiving address, which appears scratched: ZRADJOYBLOZJITZZSDKMFPCWAUARROTCNOGOILQ9DHAKLPG9GPLTITDFSZMDJKXJLGTIYDHGNMKTLRIGZCEXREWVAD]
3. [and so on...]

**Expected behavior:** [canceling the transfer, to restore my funds, suggests improvements in the system such as passwords and e-mail notifications of transactions.]

**Actual behavior:** [just waiting..]

### Versions

[windows 10]
[iota light wallat 2.5.7 - iri 2.4.2.1]
![iotawallet01](https://user-images.githubusercontent.com/36332797/36062880-cd0a9de4-0e6c-11e8-88de-e1803917ada8.jpg)
![iotawallet02](https://user-images.githubusercontent.com/36332797/36062881-d1d117ea-0e6c-11e8-8799-63bfbd3c14f8.jpg)

**Comment by wonkytonky** [comment]
if you didnt move that money out.. it's  gone , seems  that guy stole from multiple people

**Comment by RPL961** [comment]
the wallet seems to be the weakness of the iota, is so vulnerable,
difficult to interact with the user, which seems to be purposely designed
for fraudulent scheme.

2018-02-10 11:27 GMT-03:00 wonkytonky <notifications@github.com>:

**Comment by NelsonNS** [comment]
RPL961
I had the same thing happen to me the other day. We have the same transaction number as well. This individual has been targeting IOTA Wallets and if you do a Google search you will see how many victims are out there due to this person. I would take this as a blessing and just walk away from this useless IOTA. They can't even produce a proper wallet, so what  makes anyone think they can actual produce a proper product. Save your money on something more meaningful that this worthless product. There are many other crypto I have found that is worth investing in. I took a risk on IOTA and good thing I found out early, I can walkaway and save my money.

**Comment by RPL961** [comment]
I could lose but it could be worse .. I was about to deposit a large sum;
the guy was able to create a custom receiver account, starting with NOFUK,
which is not allowed to ordinary user, i guess.

2018-02-10 14:40 GMT-03:00 NelsonNS <notifications@github.com>:

**Comment by NelsonNS** [comment]
I find it best to just sell off what you have and just move on. There are others that are using the IOTA thought and making it a proven concept, with an actual wallet that works. Something IOTA cannot accomplish.

**Comment by rajivshah3** [comment]
It is important to know that in decentralized cryptocurrency, **you are your own bank** and **you are responsible for keeping your funds safe**. If your funds were stolen because you used a malicious seed generator, that is not anyone else's fault. If you tell someone your banking password and they steal the money from your account, is the bank vulnerable? It's the same situation here.
