### ISSUE TITLE
2 different passwords lead to the same valid account

### ISSUE THREAD

**Issue by rennne** [iotaledger/wallet#120]
I have a passphrase consisting of 45 Letters
When I attach a "9" at the end it delivers the same account with the same balance and the same history.

**Comment by stockermans** [comment]
I think this is a non-issue...because if you make a seed with:
"AAAABBBBCCCC"
Once you input this to sign in, the wallet automatically appends "9"s to fill up to be 81 chars.
So if you had a 45 char seed of letters, and added a 9, it would be the same..since everything after these 45 chars are going to automatically be 9s.

I think it is highly recommended you don't use a 45 Letter seed. Use 81 chars.

**Comment by todofixthis** [comment]
@stockermans is correct.  The crypto functionality in IOTA uses a library called [curl](https://github.com/iotaledger/ccurl), which always operates on 81 trytes at a time.  "9" is the padding tryte used when an input is too short (it represents `000`).

@rennne If you were to put something other than a "9" at the end of your seed, that should cause the wallet to generate different addresses.
