### ISSUE TITLE
Iota disappearing.

### ISSUE THREAD

**Issue by nattitanic** [iotaledger/wallet#138]
I posted this on reddit to:

"Hi, everyone!
(I don't know if this is the place for help, but I'm desperate)
**I bought some Iota from Bitfinex and sent it to my Iota light wallet, and then:**
1)My iota was transferred into Gi
2)My Iota was sent to an unknown account.
**Here's some info:**
-I used the Iota Support Host
-I NEVER posted or shared my Seed 
-I didn't touch, my account the day it happened

Thanks!
Nathan"

Anyways, there's an issue that if your seed is too short, that there is a HUGE chance of being hacked. they should re add the seed generating tool as the version I was using didn't have one.

**Comment by atypicalprogrammer** [comment]
Next version will not allow login with invalid seed. I suppose your seed was too simple?

**Comment by craypto** [comment]
Wait!!!! I think it is an awesome feature that the wallet allows you to use a shorter seed. Im currently using a shorter seed with only small funds to test the wallet because it is easier that way. **I would really recommend that the next version doesnt change this nice feature.** Im a noob so Id be interested in hearing the other side and why this change is a good thing, but love the openness as it is right now.

**Comment by nattitanic** [comment]
Well, I think they should change it, ALL MY IOTA DISAPPEARED! Any I don't want what happened to me happen to anyone else.

**Comment by atypicalprogrammer** [comment]
There will still be an option (not checked by default) to allow login with a shorter seed.
