### ISSUE TITLE
2.3.0 laggy client, pre 2.3.0 as well

### ISSUE THREAD

**Issue by lueyforje** [iotaledger/wallet#150]
having a seed with 60 transfers/ 40-50addresses when the wallet is in focus its cpu is usually around 30%, it will go up and down, but it instantly drops cpu usage to 0-1% the moment i minimize the wallet. 

after leaving the client running for a good while, the client feels super laggy, and will stay this way until i go back to the "enter seed" area and relog.
it still works and does pow pretty quick and all just the wallet is laggy.

windows 10 64bit, 8gb ram, i5-4570 3.2ghz

**Comment by stepby7** [comment]
Lueyforje,

I have IOTA Wallet 2.3.0 installed on my desktop, I have sought advice from
a number of people here online but have still not been able to successfully
open the wallet and thereby causing me to lose out on buying IOTA.

I have tried to generate my own 81 digits seed, made up of uppercase
alphabets and figure 9 and used IOTA tool/ seed generator but have all
failed.

Example: SI99HYQJWWPYCO9TODFNEEKT9HVV9IEN9RYLMDQZCFPLGTRFZJTF9TEJVQODZPUJRZ


Each time i try inserting a seed like that i get words (NOT SYNCED) and the
stuff goes on to logging in endlessly. What can i do?


Kind regards-Steve

**Comment by atypicalprogrammer** [comment]
@lueyforje we are aware of the lag, this is mostly due to iota.lib.js project which sends way too many requests to the light node. It was initially made for full nodes, which don't experience such lag. It should be optimized in the future.

@stepby7 this is irrelevant to current issue. You simply have not enough neighbors. Go to the slack and ask around.
