### ISSUE TITLE
Seed i used and was approved earlier is now apparently more than 81 characters long, cant access my wallet

### ISSUE THREAD

**Issue by Marolus8** [iotaledger/wallet#177]

**Comment by wonkytonky** [comment]
download older wallet  try again..   make new seed 81 long..   and move money over there..  for a quickfix

**Comment by Marolus8** [comment]
but the miota on my older wallet is probably lost, but quick question, address and seed are 2 different things ? or is it the same

**Comment by Marolus8** [comment]
Still new to iota

**Comment by marcel-burkhard** [comment]
Address and seed are different things.

The seed is private, should not be given to anyone. It's like the wallet and your private keys in bitcoin for an analogy.

You generate addresses using that seed, it's deterministic and you only need to keep the seed because when you log into a wallet on a new device you will either already see your old addresses or they will appear when generating addresses and your corresponding balance will be visible.

You can share the address(es) of course, as they can not be used to find out the seed.
