### ISSUE TITLE
The New wallet updeta is showing my balance now.

### ISSUE THREAD

**Issue by AKALIY** [iotaledger/wallet#191]
Good Thanks.

**Comment by jgogurl** [comment]
I have a zero balance and I should have 1998 coins. I am a total newbee and and not sure what to do. I cannot imagine it has been stolen because it is not that much money. I saw there is an update but I am afraid to do it. I have my long generated seed so I can get in it just says zero. Please help!

**Comment by wonkytonky** [comment]
install new wallet .; follow instructions in wizard

**Comment by AKALIY** [comment]
Hello,
I sand 100Mi on 3/11/2017
Since then is pending until now please help thnks.

**Comment by rajivshah3** [comment]
You should reattach and promote this transaction until it confirms

**Comment by AKALIY** [comment]
I did but nothing.!!!
