### ISSUE TITLE
Lost funds

### ISSUE THREAD

**Issue by UnrulyHuman** [iotaledger/wallet#227]
I have a new 2.4.0. wallet. I never had an earlier wallet. I transferred my MIOTA out of Bitfinex into the wallet, it showed the correct amount. I came back a few days later, I have zero mioto, zero transaction history. I opened the receive tab and generated new addresses, thirteen times now, still zero funds.

History shows 13 transfers, 13 addresses, some still pending but all show a big 0

What do I do now? I think my Mac computer updated while I was out of town, I've looked for the the database folder in my application support folder. I don't see one.

**Comment by wonkytonky** [comment]
can you see the iota you got from bitfinex  https://iotasear.ch  ? 
did it move?  if not.. chances are  high you are not using the same seed.

**Comment by wowlwow** [comment]
I input m old seed from the Android Wallet to Windows hope to recover IOTA funds. but the 'Incomplete in Balance' only 50 address per input.  The IOTA tool cool website stated I need to reach almost 170000 Address to find my IOTAS. Possible to reprogram the wallet in Windows to ONE CLICK start searching until found?  Major program design flaw here.

**Comment by stockermans** [comment]
Either your balance that you had before has moved away (possible due to a short and insecure seed which is unsafe), or you are using an incorrect seed (it must identical 81 characters as when you made it, one difference will end up with a different account of course).

If you had generated 169000 addresses with balances on all of them, then you would need to generate that many. 

If you only ever had 12 addresses, then it would only need to create 12 addresses (out of the first 50).

**Comment by UnrulyHuman** [comment]
I indeed was 1 character off between what I thought I entered and my actual seed. Thanks

**Comment by wonkytonky** [comment]
nice,  i'd use something like keepass to manage your seeds. this way it's just copy paste seed and it will remove clipboard after a few seconds(check options i think you can set the time)

**Comment by wonkytonky** [comment]
can you close this issue?
