### ISSUE TITLE
Invalid iota address when attempting to transfer from Bitfinex

### ISSUE THREAD

**Issue by bradyswenson** [iotaledger/wallet#303]
I've installed the light wallet for OSX, logged in with a valid 81 char seed, generated an iota address, attached it to the tangle, and requested a withdraw from Bitfinex into my light wallet's receive address. 

I get this error message from Bitfinex: 
![image](https://user-images.githubusercontent.com/3144456/30517849-dc945470-9b31-11e7-91a4-7b192fc182d3.png)

I am using my wallet's receive address, not my seed.

**Comment by bradyswenson** [comment]
I see this in History, but no transfer has occurred. Ive tried clicking "Rebroadcast" as well. 

![image](https://user-images.githubusercontent.com/3144456/30521133-10e4f538-9b80-11e7-8ddd-e49aa0fa9130.png)

**Comment by wonkytonky** [comment]
this is just an address attachement. it doesnt have to confirm. 
what is important is the transactions from bitfinex to your address 
that one should be reattachable 

But due to the last bug exploit the network is very slow . so i'd wait to send money until thats fixed, a snapshot of the network will be taken to speed up this process.; 

so wait till after that if you still need to send money to your wallet.  keep an eye on announcements in slack

**Comment by bradyswenson** [comment]
Ok, thanks for the reply. Will reopen if I can't get the transfer to work after the network returns to normal operation.
