### ISSUE TITLE
Virustotal.com scan on IOTA.Wallet.Setup.2.5.1.1.exe

### ISSUE THREAD

**Issue by bad5150** [iotaledger/wallet#381]
TrendMicro returns a malware bug on IOTA.Wallet.Setup.2.5.1.1.exe
Baidu returns a malware/trojan bug on IOTA.Wallet.Setup.2.5.0.exe

...both are from Virustotal.com scans

Should I be concerned?

**Comment by visionguild** [comment]
don't use this wallet.  everyone is having their balances vanish.  mine too.

**Comment by bad5150** [comment]
Thank you! Was using Avast & it didn't catch it either. If there's any further info available as to how to safely remove those wallets and the viruses since installed would appreciate knowing.

**Comment by th0br0** [comment]
I have deleted `visionguild`' & `bad5150`'s comment. They were spreading FUD. The comment content was: 
`don't use this wallet. everyone is having their balances vanish. mine too.`

I just reanalysed the file on virustotal.com and received these results:
```
eGambit = malicious_confidence_59%
WhiteArmor = Malware.HighConfidence
```
(see https://www.virustotal.com/#/file/602ccc7904e194494a2b888a79feb2f16bd5072c532b7ac90e126f0500c19464/detection )

There's no malware in the wallet and the reporting users (both of them) are fake.

**Comment by bad5150** [comment]
Hey!

I'm new to Crypto, Bought IOTA, (one of my 1st Alt buys and SOLD it bc of
this!) Just went by a youtube that used that scan site to install the
wallet! I wasn't trying to spread FUD. I do not understand WHY it came up
on Virustotal in RED like that and simply was reporting what I saw. I'm NOT
a fake or shill and it was a VALID question. Only thing I can code is CGI &
HTML.

Dammit! I did due diligence & believed in IOTA long term but now have no
idea WHAT to believe and consider it REALLY f'd up that I consider it a
reliable tech! *It shouldn't come up RED anywhere if you expect to promote
it!*

You need to answer this question and make sense because it's still coming
up in RED *(eGambit = malicious_confidence_59%*
WhiteArmor = Malware.HighConfidence) on virustotal.

Seems to me not successfully answering will make things even WORSE for
IOTA!

Don't do that to the tech if it doesn't deserve it!

Dammit. Member of a Slack SigAlert. I need to get to the bottom of this.

Call me if you like.

Gary
208-267-8356



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by paulhandy** [comment]
What's a Slack SigAlert?

**Comment by paulhandy** [comment]
Looking at @th0br0's posted link - what would be the criteria under which eGambit and WhiteArmor listed it as potentially malicious?

**Comment by bad5150** [comment]
This issue was solved via consult w/Paul. Determined this more than likely happens due to Seed generation from phishing websites at setup & install. Believe the Wallets themselves are not the issue...the results at Virustotal  may be inaccurate. I sincerely appreciate the IOTA team clearing this up!

**Comment by visionguild** [comment]
you delete my post because it doesn't seem true to you!  I'm not trying to
start anything with Iota.  Why would I do that.  I had over 500 Iota last
night.  120 in my wallet.  the 120 are gone.  I'm not making this up.  So
about 55 dollars worth of Iota shows in the history as being sent out.
Geez, this is really how the support for Iota is?  What am I missing here.
I create a post and get called fake.  WTF?  Guess it's easier than helping
me huh.

**Comment by visionguild** [comment]
you delete my post because it doesn't seem true to you!  I'm not trying to
start anything with Iota.  Why would I do that.  I had over 500 Iota last
night.  120 in my wallet.  the 120 are gone.  I'm not making this up.  So
about 55 dollars worth of Iota shows in the history as being sent out.
Geez, this is really how the support for Iota is?  What am I missing here.
I create a post and get called fake.  WTF?  Guess it's easier than helping
me huh.

**Comment by visionguild** [comment]
you delete my post because it doesn't seem true to you!  I'm not trying to
start anything with Iota.  Why would I do that.  I had over 500 Iota last
night.  120 in my wallet.  the 120 are gone.  I'm not making this up.  So
about 55 dollars worth of Iota shows in the history as being sent out.
Geez, this is really how the support for Iota is?  What am I missing here.
I create a post and get called fake.  WTF?  Guess it's easier than helping
me huh.
