### ISSUE TITLE
No reclaim tool for Linux?

### ISSUE THREAD

**Issue by nunojusto** [iotaledger/wallet#397]
Guys, i saw the new wallet with reclaim tool windows and Mac... but nothing for Linux. Why?

**Comment by sironitomas** [comment]
I tried building it but I get errors. Anybody was able to do it?

**Comment by LaurensBrinker** [comment]
Anyone knows where I can find the new wallet release for linux?

**Comment by nunojusto** [comment]
Not good if we are being left behind the rest of the OS choices.

**Comment by Polve** [comment]
I miss the linux version too

**Comment by stockermans** [comment]
Hi guys, I'm not sure if the latest pre-release includes the tool, it might, but it has a linux .deb
Otherwise you can build it.
Get: NodeJS (node + npm), then install electron:
`npm install -g electron` (need super privileges for global install)
`npm install -g bower` (need super privileges for global install)
Now clone the wallet repo:`git clone https://github.com/iotaledger/wallet`
Inside the `wallet` folder make a folder called `iri` (use `cd` to change folders)
Inside the `iri` folder put inside there the latest iri.jar from:
https://github.com/iotaledger/iri/releases
(Saves compiling this yourself)
Now just go back into the main `wallet` folder and do:
`npm install`
When that finishes do:
`npm start`
Wallet is now running.

**Comment by th0br0** [comment]
2.5.3 includes the reclaim tool and has Linux builds available. Please use that or follow @stockerman's (thanks!) Short howto

**Comment by nunojusto** [comment]
Yeah, i see it was posted now. thanks
