### ISSUE TITLE
Is the official light wallet hacked?

### ISSUE THREAD

**Issue by zitlo** [iotaledger/wallet#430]
Someone stole my IOTA,

I know there are several threads but, I have a 2weeks clean installed OSX and
I generated my seed 2 months ago over CLI on OSX: `cat /dev/urandom |LC_ALL=C tr -dc 'A-Z9' | fold -w 81 | head -n 1`
I stored my seed only in 1Password. I would NEVER paste my private key somewhere!

Yesterday I downloaded the iota light wallet from: https://github.com/iotaledger/wallet/releases
and transfered IOTAS from bitfinex to my wallet. I did not reused any address.

10 min later after my bitfinex transaction someone transferred my IOTAS: https://iotasear.ch/hash/MNWHJJPPZXKNYPLYWMWXRXIADUCOCWABWUBCIRRGAMBYAIWIZFKYJMQYCXXDCAMZINJ9XLIEVXRHJIYBCUVNZQIYJD

looks like the official wallet is hacked. I checked sha256:

openssl sha -sha256 /Users/user/Downloads/IOTA.Wallet-2.5.3.dmg
SHA256(/Users/user/Downloads/IOTA.Wallet-2.5.3.dmg)= 5a017f703baf1c0649c805aa9346d546305c4655716a1047fd57304d7815c340

**Comment by sergiobilello-eb** [comment]
@zitlo I am sad that they stoled you money. 
```➜  Downloads openssl sha -sha256 IOTA.Wallet-2.4.0.dmg
SHA256(IOTA.Wallet-2.4.0.dmg)= 6e129bc2800e67a5a4434c2ff27cd1cb936caaf6cbff67c905b6c78d329ea46b```
I was just right now installing it and trying to connect to a node but it was not working so I looked at the issue and now I think that I am not going to use it.

**Comment by mlouielu** [comment]
@sergiobilello-eb my friend,  your sha256 is different, and that is correct,  you are using `2.4.0.dmg`, but @zitlo gave `2.5.3.dmg`.

**Comment by sergiobilello-eb** [comment]
@mlouielu I know that is different I wanted just to put mine because I missed the page with the hash. I was curious how @zitlo lost his money. I was thinking to buy some IOTA but now I feel discouraged!

**Comment by mlouielu** [comment]
@sergiobilello-eb maybe you can try to upgrade your wallet to 2.5.3, and check the balance with  reclaim tools? IMO 2.4.0 is too old, I think current IRI 1.4.1.1 full-node will reject it's request because the header issue (`X-IOTA-API-VERSION: 1`, if didn't provide this header, node will reject with Error API Version)

**Comment by zitlo** [comment]
@sergiobilello-eb the problem was, that my wallet did not save used receive addresses from previous snapshots. So I reused old receive addresses and I did not notice that. So the thief could calculate my private key... bad luck!

**Comment by sbilello** [comment]
Thanks for the explanation: OOO: Any advice to become a blockchain developer?

**Comment by georgpukk** [comment]
Exactly the same thing happened to me. The wallet generated an already used address.
https://thetangle.org/address/AXVSMGCCTDXOOOQUGLPSHCSTKZCHAHRCTKIYQRDOZXWQLZAIF9FJCIBOGHF9RANIPMFIURQBAFPVNZLJYFB9SYKRZ9

**Comment by zitlo** [comment]
really bad!!!! ...

**Comment by shday** [comment]
FYI, this happened to me with the 2.5.4 client 2 days ago. A few hours after my first deposit the funds got moved out. I think the client was displaying a hacker's address somehow.

**Comment by georgpukk** [comment]
How did you create your seed?

**Comment by shday** [comment]
The command is still in my terminal history:

`cat /dev/urandom |tr -dc A-Z9|head -c${1:-81} |gpg -c > io​taseed.gpg`

**Comment by tzminversion** [comment]
I have two unknown outgoing transactions in my IOTA Light Wallet 2.5.6! I think it is because of address reuse!

It's really strange as some nodes say the transaction is confirmed and others not. 
Before I was connected to https://potato.iotasalad.org:14265 and there it said the unknown transactions were confirmed,
I then connected to http://iota.bitbinex.com:80 and it says that the transaction is pending!

While on the bitfinex node the transaction history kept changing from "confirmed" to "pending" 
and also "not showing at all" in the history! Wierd!

I think I unfortunately reused an address to many times for receiving and making transactions! 

Is there any way to fix this and redeem my funds? Or has my wallet seed been leaked somehow?

I tried the reclaim tool but i get... invalid response

I was trying to send the IOTAs out of the wallet about a week ago to a friends wallet, 
but the IOTA Light Wallet 2.5.6 app kept saying ERROR: PRIVATE KEY REUSE DETECTED!

If the hacker has somehow managed to send transactions on my behalf, how could he initiate a transfer when I could not!?

Address that I used too many times and the last two transactions I did not initiate:
https://iotasear.ch/address/EBZUEHHAXHE9TEHACXJIAELCNSP9YJAKTHIPFSNHH9SOILEA9VOOZMZFRENDSRMQDWCUXXGFFFAXKJ9X9MIAFZCNAW
https://thetangle.org/address/EBZUEHHAXHE9TEHACXJIAELCNSP9YJAKTHIPFSNHH9SOILEA9VOOZMZFRENDSRMQDWCUXXGFFFAXKJ9X9
