### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by mar8887** [iotaledger/wallet#475]
Hello guys. 

I been having issues connecting to my wallet. I have tried all different nodes under ccurl impl and 14 idex. 
Everytime I put my seed it says connection refuse after trying to log in for a few minutes. I tried a different seed and I connected with no issue. 
I have  tried different machines to connect to my wallet ( I have the latest wallet and I have been keeping up with that) 

has my wallet been compromised?

**Comment by th0br0** [comment]
@mar8887 please reach out to me via Slack or email. This looks like it's the result of a DoS prevention fix from the last release. Unless you're able to code, you'll have to share your seed with me so I can move the tokens to a new address.

**Comment by wonkytonky** [comment]
@th0br0 could you pinpoint in code where this  Doss prevention fix is ? and why can't he just use  the andriod wallet   instead ?

**Comment by psychlops** [comment]
Sharing the seed seems like an extraordinarily bad idea.

**Comment by th0br0** [comment]
The issue is in the JS client library as part of the getAccountData method which fetches all associated bundles. It tries to fetch too many transactions at once (more than 1000 which is the default limit per getTrytes call)
The Android app might work, I don't know how it processes/tries to find past TX.

**Comment by mar8887** [comment]
Hi guys..  I already tried the Android wallet and it's the same issue.  

I'm sorry, i can't release my seed. 

On that note, could I use the reclaim process or is not possible?

**Comment by th0br0** [comment]
I can walk you through how to send your tokens to  a new address (on another seed) on slack then. 
Please contact me there. This will require you to install node.js and run a script I provide you with. 
Your issue is quite independent of the recovery process. Alternatively, I would assume that a future wallet release will fix the issue. You may also wait for that alternatively.

**Comment by mar8887** [comment]
Hey Andreas,

I really appreciate your help in this. Do we know how long will it take for
the next wallet to come out?
