### ISSUE TITLE
Issue regarding possibly compromised IOTA account.

### ISSUE THREAD

**Issue by gitdisrupt** [iotaledger/wallet#635]
**PLEASE HELP.**

**TRANSACTION IS STILL PENDING, I AM HOPING SOMEONE CAN HELP BEFORE TOO LATE.**

Starting balance 241 Mi.

I am raising this issue because i saw an INCORRECT withdraw TX listed while connected to bitfinex node.

i attempted a "send" of just -4Mi .... but saw a TX while connected to the bitfinex node that showed a pending "send" TX of my full balance of -241Mi. 

**THIS MY ACCOUNT**
https://iotasear.ch/address/ZQJWQAEGAJOGPVCOXWV9YHCYG9KOJXJIDITZPVDTTQEVOKAOQOXMK9BWJOZFPNOFPVGZND9I9LSIB9JRXQBKQFQCMY

**HERE ARE THE STEPS I TOOK:**

My seed was offline. I connected the external drive that contains it in-order to log into the wallet version 2.5.4. on Mac OSX.

I logged in with lite wallet setting while connected to the node: `node02.iotatoken.nl:14265`

All seemed ok. I had a total of 241 Mi in my account.

I attempted to send 4 Mi to my Bitfinex IOTA address as a test.

Withdrawal Transaction for -4Mi (with red arrow) was pending.

After 40 min, it was still pending so, i logged out, and changed node to `iota.bitfinex.com:80` thinking i would attempted a "REATTACH" on that node in-order to get it to confirm quicker.

**The "REATTACH" completed, but then i saw a withdrawal (with red arrow) for my total balance which should NOT have been there. It should have read as -4Mi and NOT -241Mi.**

In FEAR of loosing my balance, i quit the wallet, re-opened, connected back to the node i was using previously: `node02.iotatoken.nl:14265`

While connected to the `node02.iotatoken.nl:14265` node, i saw a withdrawal (with red arrow) for -4Mi which is correct.

the transaction which showed -214Mi _pending_ as a withdrawal, only appeared when connected to the bitfinex node.

In an attempt to **PROTECT MY BALANCE**, i created a **NEW** seed ... generated a receive address and attached it to the tangle. I then logged back into my original account on the `node02.iotatoken.nl:14265` node and i attempted to send a total of **237 Mi** to that new receive address in an attempt to rescue and protect my balance it but i get the error: **"PRIVATE KEY REUSE DETECTED!"**

I am trying to re-connect to the bitfinex node to see if the strange TX is still there, but now i cannot connect to the node. It seems like it is offline.

**WAS I HACKED? OR IS MY BALANCE SAFE?**

I sincerely hope someone from IOTA will respond to this.

I have never reused a receive address, and my seed was not compromised, other then the fact that i used it to log in using the wallet 2.5.4 to both the bitfinex node and iotatoken nodes 01-03

I have since tried 3 additional "REATTACH" methods on `node02.iotatoken.nl:14265` in an attempt to get the TX for the -4Mi withdrawal to confirm, but still no luck.

Still cannot connect to the bitfinex node. Trying and will update here once i do.

**Comment by thermalcoin** [comment]
Similar issue
i used android wallet
And hackers hijacked one of my addresses because android wallet kept trying to move funds from address to address (in every new bundle txs)
A hefty amount of iota was stolen from me.
Devs wont answer you they dont care.

**Comment by arancauchi** [comment]
It's not that we don't care. We do care, but the issues you have raised are always 100% of the time user error. This means that we have to explain to every user every time how they made a mistake and compromised their seed. Thousands of people have done this in my estimation, and it is entirely not the foundation or the wider community's responsibility to fix this. This is an open source project, with very clear guidance about what you can and can't do with the protocol. If you make a mistake, that is your fault. If you want someone to control your money and get it back, use a bank. Crypto does not work this way.

**Comment by gitdisrupt** [comment]
i never suggested you do not care ....

First of all ... because all of these TX are still pending i still cannot determine if all is ok.

The explorer is confusing ....

Are you able to check an address for ALL pending TX's ?

There should only be 1 TX today sending 4Mi
and NOT my full balance of 241Mi

Here is my address: ZQJWQAEGAJOGPVCOXWV9YHCYG9KOJXJIDITZPVDTTQEVOKAOQOXMK9BWJOZFPNOFPVGZND9I9LSIB9JRXQBKQFQCMY

**Comment by thermalcoin** [comment]
when u publish a wallet that re-uses an address and bundles it with your intended tx. And keep reusing the address because previous tx wasnt confirmed. That u have a buggy wallet. The android wallet screwed alot of people including me. How was i supposed to know it was trying to send from the same address every time. Compromised my address.

Not to mention the unconfirmed txs for days. Its simply not functionnal. 10 confirmations per minute??? thats barely 0.2 tx per second...

**Comment by gitdisrupt** [comment]
Here is a simple question ....
By simply looking here: https://iotasear.ch/address/ZQJWQAEGAJOGPVCOXWV9YHCYG9KOJXJIDITZPVDTTQEVOKAOQOXMK9BWJOZFPNOFPVGZND9I9LSIB9JRXQBKQFQCMY

Can i be SURE that there are no other TX's pending?

The explorer is NOT clear...

It looks like by "sending" an amount ... the FULL BALANCE is withdrawn automatically from the original address, the wallet generates a NEW address and deposits the balance of the original to it.

Is that correct??

**Comment by gitdisrupt** [comment]
also @arancauchi i understand that you probably do have to deal with a lot of people that do not know what they are doing, but i do know how to protect my seed.

Please do not assume that ALL people have made errors on their part.

I am just trying to get a clear answer from ANYone that will help about how to check for ALL pending TX for a particular account / seed.

Is that such a hard thing to ask for?

ANY help greatly appreciated.

**Comment by gitdisrupt** [comment]
@arancauchi i have updated the issue above. Hope you or someone else might take a min to respond. Apologies if you got the wrong impression from me or anyone else responding on this thread.

**Comment by justin504** [comment]
@gitdisrupt Here is something I posted to reddit to save my balance which was in an outward pending transaction

This will only work if the thief's transaction is still pending. BUMP TO TOP, LINK ANYONE WHOSE FUNDS ARE STOLEN

Download the Android Iota Application from Google Play. If you do not have google products, use a friend's or if you have windows, download a software from www.bluestacks.com, it allows you to access Google Play. Follow the setup procedures, log in or create Google Account. Download Iota Wallet.
Use Android Wallet to send all of your Iotas to another address you have access to, be that an exchange address or another wallet with a new seed. If you create a new wallet, use other people's advice on creating a new seed. I can't help you there. DO NOT USE ANY ONLINE SEED GENERATOR.

Send transaction from android wallet. MAKE SURE YOU SELECT THE CORRECT PREFIX (Mi, Gi, etc. if you don't select, it will simply send the smallest amount). After you send transaction from android wallet. Click on transaction and reattach. For the reattaching, I just went to my desktop client with the compromised seed because the android app was too slow. I connected to nodes with lowest pings. I assume that depends on your location. Those can be found here: https://iota.dance/nodes

REATTACH AND REATTACH some more. First reattach from the node with the lowest ping. Then log out, log back in and connect to the node with the second lowest ping. Reattach again.Then log out/log back in to the node with the third lowest ping. Reattach again.

*Make sure you send to a secure address, make sure you select correct prefix when sending, reattach from different low ping nodes. I had some issues with android app - not connecting to nodes, I simply logged out, logged back in / not showing balance - click on addresses option and hit refresh or scroll up and down a ton of times.

If you were able to save your stolen funds and would like to donate:
ETH: 0x0343A5De943aed9dc5078208AFc8a4FeDC959648
DASH: XtSXpAEXhbAdoNCnKKmiQJZAEavQck3p18
XRP: rU52rjdDn1ZBEHzhD4huazMk6MFD5BuUbj
BTC: 1Cu6B3UzrjSFig4437KC7ENW9hamMHNBB5
LTC: LgUmJAzVxHDmBQ1vvnhGrvYLPkGwStnmsZ
VTC: Vo1VKcjTVyZan2Mn5my2tdkyZcE3VdW4sv

**Comment by justin504** [comment]
@gitdisrupt I hope you save your balance! Mine was almost stolen, I spent 12+ hours researching yesterday and was able to save it. Very grateful

**Comment by justin504** [comment]
@gitdisrupt search "stolen iota pending" on reddit

**Comment by patchthecode** [comment]
@arancauchi 

> ...the issues you have raised are always 100% of the time user error. 
Thousands of people have done this it is.. not the foundation or the wider community's responsibility to fix this.
 If you make a mistake, that is your fault. If you want someone to control your money and get it back, use a bank.
This protocol is in BETA, which means you accept all liability for problems that may arise. 
That risk is on YOU.

wow, you know.. you may be an a$$-hole. And hey, its your right to be one. 
Heck, even I'm an a$$hole. 
But you know what? Since this product is getting more steam and hoards of noobs who are totally NON-TECHNICAL-PEOPLE are starting to use it, can you please try **_not_** to be one? Thanks.

Many noobs just coming into the crypto world are not expecting a product that is riddled with so many ways, which can get their money STOLEN if they are not careful; no matter how many warnings you post, or how many heaps of tutorials you give them for your Beta product (more like Alpha in my opinion). Please dont forget a major rule in programming systems that rely on security --> _People are stupid. Make your product idiot proof._

**Comment by gitdisrupt** [comment]
I was able to determine that my balance is still there. The transaction data in the explorer and the wallet is confusing and should be clearer. I was completely mislead to believe something bad was going on due to how the transaction data tries to outline how the final balance is calculated.
