### ISSUE TITLE
5 hours and 3 versions later... can't connect to remote node

### ISSUE THREAD

**Issue by cnpalmer83** [iotaledger/wallet#812]
OS: Linux Mint
Wallet version 2.5.5 (Lite)
GUI issues: Wallet is a blank window.... list of hosts empty.
Status bar: Starts out with CPU ~18%... eventually shows CPU 0.00%

Is this just a timeout issue?  I really want to stock up on IOTA... but that's just not going to happen if I can't store it somewhere safe.

**Comment by zenmetsu** [comment]
I think that the network is the problem.  I have not managed to get an address attached to the tangle via the linux client.  It works on the android client after about a dozen attempts.  I think that the network is overly taxed at the moment.  The exchanges that do have IOTA markets have suspended IOTA withdrawals due to the network issues, so you likely wouldn't have much luck moving IOTA even if your lite wallet was working.
