### ISSUE TITLE
IOTA transaction pending for weeks

### ISSUE THREAD

**Issue by SmokinCaterpillar** [iotaledger/wallet#822]
Hi, I did a test transaction with the 2.5.4 wallet (updated to 2.5.5 today) and this turned out to be an epic failure!

My transaction has been pending for ridiculous 17 days now! Despite numerous re-attachments, node changes ,and re-broadcasting.

What is wrong, why is no-one verifying my transaction?

Explorer link:
https://iotasear.ch/hash/EXAEGHFEZZSFRFESCRMRGXLVLOJVYZVUX9AQLXMCXXJYYXMHQSSAYYWOPZUEBBVTMSHENAAQTUEI99999

**Comment by mgrassotti** [comment]
Can it depend from the amount of the transaction? I am having the same issue for a 827ki transaction, while I got successful transfers in a few reattachments for transactions of more than 100Mi.

**Comment by samgranger** [comment]
That node should be fine. What weight are you using? This should be set to 14.

**Comment by mgrassotti** [comment]
Yes
Min Weight Magnitude: 14
Curl Implementation: Webgl 2 Curl Implementation

With wallet version 2.2.5 I have seen now there is "Promote" instead of "Reattach", but the effect seems to be the same...

**Comment by mgrassotti** [comment]
Ah now it magically worked 😄 but I am wondering if this is just network congestion or something else is involved...

**Comment by SmokinCaterpillar** [comment]
@samgranger I use 15 minimum weight and I do not find `http://03.nl.nodes.iota.cafe:14265` in my list of available nodes. I am connected to `http://node05.iotatoken.nl:16265`.

**Comment by samgranger** [comment]
You can manually add nodes (option in the dropdown). Using a minimum weight above 14 just means it takes longer to finish PoW / not necessary.

**Comment by SmokinCaterpillar** [comment]
What are the risks of adding custom nodes? Do the nodes get to see the seed? I hope they don't, they only receive signed transactions, right?

**Comment by mgrassotti** [comment]
I am not an expert but they surely cannot. If one could see your seed also the others could.

**Comment by wonkytonky** [comment]
nodes never see seed

**Comment by SmokinCaterpillar** [comment]
Switching to `http://03.nl.nodes.iota.cafe:14265`, re-attaching and promoting did not help. Still stuck, twenty re-attachments and counting... -.-

**Comment by yntrader** [comment]
I have been unable to transfer Iota from wallet to Binance for 15 days now. Very frustrating. Hard to find the value in this coin and wallet if it is a "Deposit Only". Feels like a roach motel.

**Comment by kalessin** [comment]
Same problem here. I tried lots of rebroadcast, reattaches, node changes, now also promotions with new version. My transaction is pending since 7 days ago and I can't do any new transaction until that one become confirmed.

**Comment by SmokinCaterpillar** [comment]
Yes, I have the same problem. Initially I wanted to move all my Iotas out of the shady Bitfinex, I made a test transaction with 3 Iotas, which went through nicely. 

However, I tried to send  1Ki further on to see if the wallet works, and this transaction is stuck now for 18 days. I also cannot send any other transaction until this transaction is confirmed! 

My level of confidence in IOTA is at a pretty low. Glad I bought them when their price was rock bottom.  I do not understand how a MarketCap of 14 billion is justified with the current state of the network.

**Comment by publicocean0** [comment]
maybe it is necessary to add in the iri node a parameter measuring the overload, when the node is too much overloaded it pass the job to another with less load. I could resolve all these problems

**Comment by kalessin** [comment]
I explained in another forum that the big problem that iota has are one of its most promoted features: zero transaction fees. Zero transaction fees doesn't encourage to support the network. There are very few nodes, nodes are expensive in resources (network BW and disk storage), and this makes most users by far (lot of orders of magnitude) only use light wallets.

There may be technical issues still to solve regarding how the tangle works. But the biggest problem iota has is not technical, but economical, and is only due to a bad design issue easy to solve.

I don't understand what people has against paying for a service. It is a bad philosophy. That never worked, lead to the tragedy of the commons. And paying for a service encourages good service and good assignation of resources.

**Comment by publicocean0** [comment]
the main scope of iota is not create a trading market in which your opinion could be correct but create a world where machines make payment for ours. The problem is for consensus you need the confirmation from other machines but there is no strategy that random machine is making the confirmation is able to do it in few seconds. If i m unlucky  it can happen a long delay also if normally and  the iota network is free in average. So the problem is to grant the shortest path in time for receiving a answer.

**Comment by kalessin** [comment]
You cannot solve any problem if there are not enough resources, no matter how well designed is the consensus protocol. Even the best ideas from technical point of view, fail when they ignore the economic equation of costs and benefits.

**Comment by ALEX778899** [comment]
Maybe reattach.online could help :-)

**Comment by publicocean0** [comment]
You are right surelly but my impression is iota , as is, can t reach response times necessary for IOT world . The power of distributed systems is to be indipendent and massive. If just few datacenters can make it because they have a indirect  gain to do it for their business, there will be always a group of people having the power to manipulate the world. Logically if you have 2 group : one owns the system and one not : you can always create a separated interest to manipulate the system for opportunity. The system must remains fattively owns by all, so the interest is superimposable with the all people interest. This is a little axiom could be trially proved. the  Bitcoin lesson is : pay few money in distributed way for making what it was made before by few banks. So the basic idea to pay for computation help, is right and it is really basic for a real democratic system. But maybe the payment might be done not for generating money using a hard pow. The pow for my opinion is to remove absolutly because is socially not supportable(the energy used and not only for it). If you understand it you can pass over to find the winner solution. The pow is not the only way for blocking flooding attacks. Simply you can pay the node with a fee for the simple and fast computation for confirmation( fee regulated automatically by the network using  a cap algo). So the people not for computing useless computations but for making a real work necessary for the networks. You earns for many little transactions not for few and long transactions!

**Comment by mgrassotti** [comment]
@kalessin I think the big idea behind IOTA is not that you are _not_ paying for a service, but indeed you _are_ paying for a service _with your own calculation power_. Each transaction involves the creation of a new node (from your wallet) which validates its own transaction and then validates other 2 unvalidated transactions. So it is a distributed power network. With Bitcoin you are paying some other people for doing that (miners), but it also leads to congestion problems and also to very high transaction fees now. Also it could lead to a few corporation who have the financial power to be strong miners to have more relevance in the network. I think IOTA is trying to avoid this. Of course it is a very new technology and it has still some problems.

**Comment by kalessin** [comment]
@publicocean0 regarding PoW, it is right what you say. I am not saying to use PoW. There are many alternatives to it. And Iota tangle may be a good solution. I am only saying that there are no incentives to support the network if there is no transaction fee. It doesn't matter how good is the idea. If costs of running a node are above its benefits, then the network will not escalate. Evenmore, as more people do transactions in the network, more costs are paid by the actual nodes, with no benefits in exchange. That will only destroy the network.

**Comment by kalessin** [comment]
@mgrassotti you don't need to have a full node to validate transactions. It is enough with the light one. The problem is that there are no incentives to run full nodes.

And comparing with bitcoin doesn't makes iota good. I repeat again: I am not discussing a technical problem of iota. I am discussing an economic problem: there are no economical incentives to support the network. And we are already suffering that. Bitcoin has congestions not because of economical issues, but because of technical ones. Iota tries to solve technical problems that bitcoin has, but on the other hand creates to itself an economical problem that bitcoin doesn't have.

And the result? regardless its problems, bitcoin works much better than iota. On the other hand, there are many other cryptocurrencies that solves the problem of bitcoin, but still has transaction fees. Without transaction fees, iota can't compete even with bitcoin.

**Comment by mgrassotti** [comment]
@kalessin I don't wont to argue with you, but I didn't say you need a full node indeed. Also I think technical problems and economical problems are not independent. Technical problems lead to economical problems. Inefficient systems make people move money away, while efficient systems attract money. And, on the other side, I don't think you can fix them just putting money inside the system (creating a transaction fee for example). I think bitcoin will lose its power right due to transaction fees. Also it could have less problems of speed now just because there are much less transactions per user (as you pay a significant amount of money for them). Have a look to the volume exchanges per currency pair on bitfinex (last number on the right in the table): 
<img width="302" alt="schermata 2017-12-21 alle 13 55 36" src="https://user-images.githubusercontent.com/6908677/34256691-d264b286-e656-11e7-87f8-b76c4df19617.png">
If I didn't completely misunderstood this number, you can see the amount of IOTA exchanges is thousands times superior to BTC ones.
I think if people behind IOTA foundation could explain (if possible) a clear and simple way to make people contribute to its speed, we won't have these problems anymore and IOTA will explode in usage.

**Comment by kalessin** [comment]
I am not saying that technical problems are independent of economical ones. Neither I am saying that you will fix technical problems putting money. Evenmore, if it was that, I hadn't say that bitcoin has technical problems. However, I said that bitcoin has technical problems but not economical ones. The only thing I am saying about IOTA is that it has a big economical problem that will not allow to escalate the network, no matter how much technical problems are solved. IOTA network spends resources, it is not free for the people that runs nodes. And someone has to pay for those costs.

Regarding the trading volumes, there are two problems in your argumentation:

1. that is only the volume of bitfinex. You can compare the global volume here, where you can see that at this moment, the volume of bitcoin trading is 50 times bigger than the volume of IOTA one:

https://coinmarketcap.com/all/views/all/

Also, more volume doesn't necessarily implies more transactions. Exchanges use internal accounting balances for trading (otherwise trading would be extremely slow), and only use native transactions when you withdraw or deposit funds, and also some internal balance correction. So the biggest part of trading occurs within exchange system and doesn't use the blockchain/tangle.

**Comment by kalessin** [comment]
«that could be exponentially bigger, as they are completely free.»

You only see the problem from the users point of view: the demand. But not from the servers point of view: the supply. Free things lead to huge demand, but to scarce supply. The network doesn't scale only with demand. Someone has to pay the costs. Iota can explode in usage, but if it doesn't explode in support, the network doesn't work. This is what is happening now. Those are basic economical concepts that can't be ignored.

And if people behind IOTA foundation doesn't want to understand this, they are not part of the solution and will not provide any solution. On the contrary they are part of the problem.

**Comment by mgrassotti** [comment]
@kalessin I could be a little naive, but I am only seeing this from the users point of view, because that is how IOTA was intended in my opinion. 
In IOTA there is no distinction between suppliers and consumers, all nodes are equally "important". From what I read here https://forum.iota.org/t/iota-nodes-infrastructure/6362/5, also light node wallets do the hard part of the work, so you are not fully relying on the full nodes for the scalability of the network. I used market capitalization just to give an idea of how much attention IOTA has right now and how much it is growing, even if it is not directly related to the number of its network transactions. 

Said that, I really don't have any clue why the network is slow at the moment. It could be because nodes are free as you said, but I don't think introducing fees is a good solution. What I think instead is, that, if you want higher speed, you should set up your full node or you can have a look at http://iota.dance/nodes to select the best ones. In IOTA any device contribute to the network. It's not consumer vs producer, it's a peer-to-peer system.

**Comment by KhanhDam** [comment]
> With wallet version 2.2.5 I have seen now there is "Promote" instead of "Reattach", but the effect seems to be the same...

No, it's different, reattach mean you still have 1 transaction/address. I've tried promoting and now I have 2 transactions/address.

**Comment by kalessin** [comment]
@mgrassotti it doesn't matter what are the intentions of IOTA. This is not a philosophical discussion. The problem is economical, not philosophical. The thing is: there is no incentive to run a full node if the benefits don't pay the costs. And philosphical justification will not pay the economical costs of running a node. And yes, In IOTA there are consumers and suppliers. That doesn't depend on phylosophy but on economics. You have people supplying full nodes, which are expensive and absolutely needed for the network to run, and people using the network through light wallets, which are much cheaper and uses much more resources from the full nodes than the resources it provides to the network (just a small amount of CPU for a small PoW). So:

«if you want higher speed, you should set up your full node»

you speak as if running a full node is free. It is not: you have to spend in many resources for that. Higher speed obtained for running a new node doesn't pay the costs of running it (unless there are transaction fees)

«or you can have a look at http://iota.dance/nodes to select the best ones»

The best one is poor if there are no economical incentives to support the network with more full nodes.

**Comment by samgranger** [comment]
You can also use the following tool to reattach/boost your transaction: https://boost.iotalpha.io

Just fill in your bundle hash of the transaction (not your seed or anything - you can find all the necessary details on the page above).

**Comment by iotasupp** [comment]
repair iota wallet...
https://iotarepair.org

**Comment by mgrassotti** [comment]
@kalessin 
"you speak as if running a full node is free. It is not: you have to spend in many resources for that. "
How many resources? I understood you just need a public static IP address and a machine running the IOTA IRI always on. I think you can have this from the cloud for 5$/month. For sure you cannot compare this to setup a mining machine for Bitcoin. Am I missing something?

**Comment by kalessin** [comment]
@mgrassotti if your only criteria is to compare with bitcoin resource requirements, there are many cryptocurrencies that pass the test. But not only a public static IP and any machine is enough. You require growing disk space to store the tangle (some dozens of Gb at the moment), an important network bandwidth, and, still, an important CPU power, as still you need to do some proof of work. That will cost around $100 per month. And only at the begining. Costs will be higher as the tangle and the network grows. May be not a big deal (at begining), but still much more expensive than a light wallet, and still you have to pay those costs. Why to pay those costs if you can just have a light wallet and use the resources than others are paying for?

There is not a mechanism to pair supply and demand. Light wallets grows much faster than full nodes.

BTW if I could spend initial $100/month right now for such a resource, I would support a cryptcocurrency that pays for those resources and even give me extra benefits. Proof of Stake cryptocurrencies doesn't need the hash power of PoW ones and many of them are already working very very fast. IOTA on the contrary, works much slower than bitcoin. It took me 7 days to confirm a transaction and the wasted time reattaching the transaction and trying lot of different nodes. Most of them were offline, or were out of sync. I never had to do that before. At moment is the worst cryptocurrency I ever tried. If running a full node is so beneficial for the person that runs it, I wonder why there are so few nodes online and synced at a given time. There is clearly an incentive issue there. Too many fans of IOTA but very few providing full node capacity.

**Comment by ALEX778899** [comment]
THERE ARE TOO MANY COMMENTS of a concern troll accounts (BANKS and BLOCHCHAIN companies). It's useless to try to destroy Iota, it's unbreakable and you'll loose a lot of money because it's free. IOTA is not controlled because It's kept alive by a wonderful non-profit foundation and a giant community that believes in this project. There is a great worldwide interest about IOTA, also in scientific research, it's unbreakeble, the new concept will bring a better future.

**Comment by kalessin** [comment]
@ALEX778899 I am not trying to destroy IOTA. I am only saying what IOTA unavoidably needs to be successful: to implement transaction fees. That alone doesn't guarantee success, but it is a requirement for success.

Whether IOTA will be destroyed or not, that depends on IOTA community itself, and its capacity to digest critics instead of take refugee in an ideological bubble of fanatics impervious to critics.

**Comment by AngryHippie** [comment]
Here's an excerpt from, "The Tangler", I feel like they have some good points about incentives for hosting a full node. Link to the page on the bottom.

- _You are aware of the fact that running the full-node is beneficial for the tangle topology and you want to help. (Yes, that exists)_
- _You have lots of transactions to make and don’t want to rely on a light node-server, as there is no guarantee that they are online when you need them._
- _You have a web app running and need the stable connection_
- _You want to have maximum speed, so you choose the full-node_
- _You want to have a copy of the Tangle database, that is generated when using a full-node. (good for several reasons)_
- _In the future, maybe you provide a service and earn money for a full node.The only financial argument would be:_
- _You invested and want to support the Tangle as much as possible_

https://www.tangleblog.com/2017/06/27/incentive-run-fullnode-iota/

**Comment by kalessin** [comment]
Yes, those are the typical arguments repeated everywhere. However, those were created by someone that doesn't understand at all economic action, economic choices and alternatives, cost of opportunities, etc. Any of those points considers either the costs to maintain a full node, or the existing alternatives to iota, or existing alternatives of investments, or all of those. They are very naive arguments:

- You invested and want to support the Tangle as much as possible

why paying the costs of having a full node to defend your investment when you can just withdraw your investment to another place that doesn't have those costs and instead have economic benefits?

- In the future, maybe you provide a service and earn money for a full node.

You can earn money for a full node only if you get transaction fees for that. IOTA hasn't that. And that comes back to my argument: IOTA must implement transaction fees if want to survive.

- You have a web app running and need the stable connection

why to pay the costs of a iota full node? Better use a light one and, if not enough full nodes in the network to make your needs to run fast, you can simply choice another technology where economical equation is positive. How IOTA competes with other technologies? There are blockchain solutions that runs very fast (as fast as IOTA promises to be, but realizable and already realized, as there are incentives for running nodes) and yes, you will pay transaction fees, but you will only pay for your usage, while running a full node not only doesn't guarantees your application will run fast (because just adding your node doesn't make you independent from the rest of the network), but you will pay for usage of everyone else.

The remaining points are all answered with any of those answers or a combination of them.

**Comment by mgrassotti** [comment]
@kalessin sorry, but I think your vision is quite limited.

_when you can just withdraw your investment to another place that doesn't have those costs and instead have economic benefits?_ - which alternatives are you talking about? Bitcoin or other blockchain currencies? I can't see many economic benefits from them, as you have to pay now huge transaction fees if compared to the legacy payment systems. So I think you'll have economic benefits only if they continue growing very fast if compared to the other fiat currency. And today I would prefer to continue using the old money and debit/credit cards if I have to choose by an economic point of view.

_You can earn money for a full node only if you get transaction fees for that. IOTA hasn't that. And that comes back to my argument: IOTA must implement transaction fees if want to survive._  - this would completely invalidate the IOTA purpose, i.e. micro-payments and IOT. Also that's not true, you could earn money from something else, e.g. a fee on exchange from fiat currency to IOTA. Also if more and more people will use IOTA, IOTA will increase in price and then if you have IOTA on your own, you will have a capital increase. That's where IOTA can make the more profit. It is a global technology, supported by people investing buying its shares (i.e. its currency). So yes you have all the motivation to run full nodes and I am not so sure they are expensive as you say. As you could run them from your computer too. I will try soon anyway.

And in general you see people only moved by immediate money returns. This could be true, but I would say only partially true. Sometimes people are smart or fool enough to postpone the immediate economic return to build a bigger or a game changing technology. They are willing to make an investment that will be repaid in the future and maybe even not in money, but because they want a technology that improves people life to be distributed as much as possibile.

If you only consider a strict producer/consumer view as you are doing, people like Linus Torvalds shouldn't have done what they did. And in general open source software shouldn't exist.

Merry Christmas

**Comment by SmokinCaterpillar** [comment]
Wow, this turned into a huge discussion. Fortunately, my transaction was finally approved, after 20 days! Hurray! Now it is time to move my funds from bitfinex. I close this issue.

**Comment by kalessin** [comment]
«which alternatives are you talking about? Bitcoin or other blockchain currencies? I can't see many economic benefits from them, as you have to pay now huge transaction fees if compared to the legacy payment systems. »

There are plenty of alternatives to invest outside the crypto world. Don't you think? The point is, arguing that someone would defend its investment by increasing costs is just ridiculous. Investments are not defended just adding more costs. Benefits must increase bigger than costs. And running a full node doesn't fit with that.

On the other hand, it is false that you have to pay huge transaction fees with other cryptcocoins. Seems you know only about bitcoin, iota, and few other cryptos more (well, to be honest, even bitcoin transaction fees can be small if you are not in a hurry. They may be big, but not huge). But there are already very fast options that are not only cheap in terms of transaction fees, but enough to economically sustain nodes, and even more: they allow to transfer bitcoin without using the slow bitcoin blockchain at all! (see for example https://wavesplatform.com/, and in particular, http://www.waveswiki.org/index.php?title=Features#Crypto_currencies_on_the_Waves_Blockchain) Confirmations here occur in seconds. Confirmations in IOTA occurs in hours (minimal) to days or even weeks (something never seen in any other cryptocurrency) How IOTA competes?

And third, I don't understand that attack to transaction fees as something morally bad while at the same time defending the costs of running a full node. That is a double moral argument.

My argument for defending transaction fees is not moral, it is just economical. An economical model like IOTA doesn't compete with fast, reliable, blockchains that distributes the costs among users by means of transaction fees, instead of centralize the costs over full node operators. IOTA economical model doesn't escalate. There are no incentives to run a full node for supporting the network.

Comparison with linux and open source is wrong. People writes open source software for its own interest. But the fact that other people use your code doesn't add extra costs to you. Running a full node and spending all the time for resources that others will use and you use only in a very small portion in that total, does.
