### ISSUE TITLE
IOTA wallet v2.5.5

### ISSUE THREAD

**Issue by rzkuvya** [iotaledger/wallet#835]
I was able to download v2.5.5 version  on W7 32 bit but does not want to open. Message: "unavailable for 32 bit windows"

**Comment by dennym** [comment]
Well you ran into 2 issues here. First of all W7 usually that brings its own pack of problems to just make something run on W7 these days. On the other hand iota wallet is 64bit as far as I can tell and the fix is not like flicking a switch to 32bit.
Unfortunately you only have 2 options: 
1. Upgrade your system which is recommended in general in your case
2. Wait for someone to make it run on W7 32bit but that is sort of unlikely

**Comment by rzkuvya** [comment]
Ok. Thanks Dennym for the information.
