### ISSUE TITLE
Iotas dissapearing from bitfinex excange account

### ISSUE THREAD

**Issue by Hercas** [iotaledger/wallet#880]
Hi,

For your consideration. Bought to trying minimum: 6 Mi Iotas, they stayed in Bitxinex exchange wallet, today about 15:30 noticed it left only 4.69 (without any transfers or trading). Interesting also, that minimum trading amount is 6 Mi Iotas, So needed to buy 6 more - to sell 10.69. Enough of Iotas for me! (had same issue with Rippley) other cryptos didn't show such actions.

**Comment by praveenballa** [comment]
hello. 

I don't use Bitfinex. There are two challenges you mentioned. I will try to answer based on my basic understanding. 

>  Bought to trying minimum: 6 Mi Iotas, they stayed in Bitxinex exchange wallet, today about 15:30 noticed it left only 4.69 (without any transfers or trading).

Please look at the transaction fees. This will be listed under Order History or Trade History. 

> So needed to buy 6 more - to sell 10.69. Enough of Iotas for me! (had same issue with Rippley) other cryptos didn't show such actions.

You should have checked the minimum trading amount for this particular exchange when you signed up/bought/sold. This is not an IOTA issue. 

> other cryptos didn't show such actions.

This is because IOTA is different from Bitcoin and solves micro transactions. Please understand the technology before bashing around.

Cheers.

**Comment by Hercas** [comment]
Thank you for helping - trading fee is  0.1 % (as it is written in history), but not close to (6 - 4,69 / 6 ´= 21,8 %). Basically I know how Iota differs form Bitcoin - that's why I'm interested where 2.3 M Iotas come.  And it occurs I'm not the one.

**Comment by wonkytonky** [comment]
this is not iota wallet issue.

**Comment by praveenballa** [comment]
Yes. @wonkytonky is right. Please close the ticket.

**Comment by rajivshah3** [comment]
Hi, if you have any concerns about your Bitfinex account you should contact Bitfinex
