### ISSUE TITLE
Maybe "Toggle Web Inspector" should be hidden for usual user?

### ISSUE THREAD

**Issue by coolslon** [iotaledger/wallet#99]
This menu option could be shown only if wallet started with some additional parameter like "--dev".

**Comment by atypicalprogrammer** [comment]
It's necessary to debug a bug, and I'm not sure all users know how to start the wallet with an extra param.. @domschiener  ?

**Comment by coolslon** [comment]
@atypicalprogrammer, those users who are going to debug probably can also start UI with additional param. Normal/regular user don't need debugger tools.

**Comment by todofixthis** [comment]
I'd recommend keeping it — what happens if you want to debug something, but you forgot to start the app with the `--dev` flag?  By the time you quit and relaunch the app, you might not be able to reproduce the issue anymore.

Some applications (e.g., Safari on macOS) have a preference that you can use to toggle the visibility of the developer tools menu.  If it is useful to hide the web inspector from users by default, we could take a similar approach.

Personally, I prefer to have the ability to peek under the hood and check the console for errors, but I suspect I'm not the target audience for this request (:
